# -----------------------------------------------------------------
# Exchange family contract source
# -----------------------------------------------------------------
[ContractFamily.Identity]
identity = { source = "${home}/contracts/identity/_identity.b64" }
